import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    marginRight: 20,
    marginLeft: 20,
  },
  flatListContainerHome: {
    marginBottom: 23,
    marginTop: 23,
  },
  btnSchedule: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '40%',
    borderWidth: 1,
    borderRadius: 20,
    borderColor: '#ED7635',
    padding: 7,
    marginLeft: 'auto',
  },
  btnScheduleText: {
    color: '#ED7635',
  },
  btnScheduleIcon: {
    marginRight: 5,
  },
  boxPowerBtn: {
    flexDirection: 'column',
    alignItems: 'center',
    width: '20%',
    padding: 10,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    marginBottom: 20,
    marginTop: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.12,
    shadowRadius: 2,
    elevation: 1, // для Android
  },
  boxPowerBtnBox: {
    width: 130,
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    padding: 16,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.12,
    shadowRadius: 2,
    elevation: 1,
    marginBottom: 15,
    marginRight: 15,
  },
  boxPowerBtnBoxSmall: {
    width: 79,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#ED7635',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.12,
    shadowRadius: 2,
    elevation: 1,
    marginBottom: 15,
    marginRight: 10,
  },
  powerBtnSmall: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  boxPowerBtnTextSmall: {
    fontFamily: 'SFProDisplay',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: 10,
    lineHeight: 12,
    textAlign: 'center',
    letterSpacing: 0.374,
    color: '#ED7635',
    marginBottom: 4,
  },
  boxPowerBtnText: {
    fontFamily: 'SFProDisplay',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 10,
    lineHeight: 12,
    letterSpacing: 0.374,
    color: '#212121',
  },
  boxPowerBtnTextBox: {
    display: 'flex',
    flexDirection: 'row',
  },
  titleText: {
    fontFamily: 'SFProDisplay',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: 14,
    lineHeight: 12,
    textAlign: 'center',
    letterSpacing: 0.374,
    color: '#111111',
    marginBottom: 4,
  },
  boxPowerBtnTextNameSmall: {
    fontFamily: 'SFProDisplay',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: 10,
    lineHeight: 12,
    textAlign: 'center',
    letterSpacing: 0.374,
    color: '#ED7635',
    marginBottom: 3,
    marginTop: 3,
  },
  boxPowerBtnTextName: {
    fontFamily: 'SFProDisplay',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: 12,
    lineHeight: 14,
    letterSpacing: 0.374,
    color: '#787880',
    marginBottom: 6,
  },
  boxFunctionDevices: {
    width: 130,
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    padding: 16,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.12,
    shadowRadius: 2,
    elevation: 1,
    marginBottom: 15,
  },
  boxFunctionDevicesSmall: {
    width: 79,
    heigh: 76,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#ED7635',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.12,
    shadowRadius: 2,
    elevation: 1,
    marginBottom: 15,
  },
  itemMargin: {
    marginRight: 12,
  },
  functionDevicesBtn: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  boxPowerTextName: {
    fontFamily: 'SFProDisplay',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 12,
    lineHeight: 14,
    textAlign: 'center',
    letterSpacing: 0.374,
    color: '#FFFFFF',
  },
  boxHomeDeviceFunctions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    alignItems: 'flex-start',

  },
  boxHomeDeviceFunctionsItem: {
    width: '30%',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 5,
  },
  boxDeviceFunctionsItemName: {
    fontFamily: 'SFProDisplay',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 12,
    lineHeight: 14,
    textAlign: 'center',
    letterSpacing: 0.374,
    color: '#FFFFFF',
  },
  boxDeviceFunctionsItemText: {
    fontFamily: 'SFProDisplay',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: 32,
    lineHeight: 38,
    textAlign: 'center',
    letterSpacing: 0.374,
    color: '#FFFFFF',
  },
  disabledContainer: {
    display: 'none',
  },
  boxIconSettings: {
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
});
