import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  deviceBoxHoryzontal: {
    height: 50,
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerText: {
    fontFamily: 'SFProDisplay',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 22,
    lineHeight: 28,
    letterSpacing: 0.35,
    color: '#212121',
  },
  textLightGrey: {
    fontFamily: 'SFProDisplay',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 17,
    letterSpacing: 0.374,
    color: '#686868',
    marginBottom: 24,
  },
  iconPlusBg: {
    justifyContent: 'center',
    alignItems: 'center',
    width: 26,
    height: 26,
    borderRadius: 50,
    backgroundColor: '#EB7535',
  },
  iconPlusBgSmall: {
    justifyContent: 'center',
    alignItems: 'center',
    width: 16,
    height: 16,
    borderRadius: 50,
    backgroundColor: '#EB7535',
  },
  borderHighlight: {
    borderWidth: 2,
    borderColor: '#EB7535',
  },
  container: {
    flex: 1,
    marginRight: 20,
    marginLeft: 20,
  },
  flatListContainer: {
    flex: 1,
    justifyContent: 'center',
    marginBottom: 10,
  },
  containerCardDevices: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    width: '46%',
    padding: 10,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    marginBottom: '4%',
    marginLeft: '2%',
    marginRight: '2%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.12,
    shadowRadius: 2,
    elevation: 1, // для Android
  },
  textNameCard: {
    fontFamily: 'SFProDisplay',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: 16,
    textAlign: 'left',
    lineHeight: 19,
    letterSpacing: 0.374,
    color: '#212121',
    marginBottom: 12,
  },
  textDescriptionCard: {
    fontFamily: 'SFProDisplayLight',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 17,
    letterSpacing: 0.374,
    color: '#212121',
  },
  button: {
    backgroundColor: '#EB7535',
    borderRadius: 5,
    paddingVertical: 10,
    paddingHorizontal: 20,
    alignSelf: 'center',
  },
  buttonText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 16,
  },
  textOff: {
    fontFamily: 'SFProDisplayLight',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 17,
    letterSpacing: 0.374,
    color: '#787880',
    paddingTop: 15,
    paddingBottom: 20,
  },
  textOn: {
    fontFamily: 'SFProDisplayLight',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 17,
    letterSpacing: 0.374,
    color: '#2BC944',
    paddingTop: 15,
    paddingBottom: 20,
  },
  textAddBox: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingTop: 15,
    paddingBottom: 20,
  },
  textAdd: {
    fontFamily: 'SFProDisplay',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: 14,
    lineHeight: 17,
    letterSpacing: 0.374,
    color: '#ED7635',
    marginRight: 5,
  },
  opacity50: {
    opacity: 0.5,
  },
  deviceImage: {
    width: '100%',
    height: undefined,
    aspectRatio: 1,
    marginBottom: 10,
  },
  deviceNotImageBox: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  deviceNotImage: {
    minWidth: '30%',
    minHeight: '30%',
    aspectRatio: 1,
    marginBottom: 10,
  },
});
