import {
  StyleSheet,
} from 'react-native';
import { responsiveFontSize } from 'react-native-responsive-dimensions';


export const styles = StyleSheet.create({
  container: {
    flex: 1,
    marginRight: 20,
    marginLeft: 20,
    flexDirection: 'column',
    justifyContent: 'space-between',
  },
  headerTextSettings: {
    fontFamily: 'SFProDisplayBold',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: responsiveFontSize(2.5),
    alignItems: 'center',
    textAlign: 'center',
    color: '#222222',
    marginBottom: 25,
  },
  cardUserDataHeaderText: {
    fontFamily: 'SFProDisplayBold',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: responsiveFontSize(2.5),
    alignItems: 'center',
    color: '#222222',
    marginBottom: 15,
  },
  cardUserBox: {
    alignItems: 'flex-start',
    justifyContent: 'center',
    padding: 16,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.12,
    shadowRadius: 2,
    elevation: 1,
    marginBottom: 15,
  },
  cardUserNumberOfDevicesBox: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 22,
  },
  cardUserBtnBox: {
    width: '100%',
    marginTop: 25,
  },
  btnBoxNotRegister: {
    flexGrow: 1,
    justifyContent: 'flex-end',
    marginTop: 'auto',
    paddingLeft: 20,
    paddingRight: 20,
  },
  cardUserName: {
    fontFamily: 'SFProDisplay',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 22,
    alignItems: 'center',
    color: '#212121',
    marginBottom: 12,
  },
  cardUserOrganization: {
    fontFamily: 'SFProDisplay',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: responsiveFontSize(2.1),
    alignItems: 'center',
    color: '#212121',
    marginBottom: 8,
  },
  cardUserNumberOfDevicesText: {
    fontFamily: 'SFProDisplay',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: responsiveFontSize(2.1),
    alignItems: 'center',
    color: '#212121',
  },
  cardUserDataBox: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    alignItems: 'center',
    marginBottom: 12,
  },
  btnDevices: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  textOff: {
    fontFamily: 'SFProDisplayLight',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: responsiveFontSize(1.8),
    color: '#787880',
  },
});
